# Generated by Django 5.0.4 on 2024-04-15 13:30

import django.db.models.deletion
import django_countries.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('premiere_date', models.DateField(verbose_name='Дата премьеры')),
                ('announcement_date', models.DateField(blank=True, null=True, verbose_name='Дата анонса')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='film_covers/', verbose_name='Обложка')),
                ('annotation', models.CharField(blank=True, max_length=255, verbose_name='Аннотация')),
                ('adult_content', models.BooleanField(verbose_name='Контент для взрослых')),
                ('publication_status', models.BooleanField(default=False, verbose_name='Статус публикации')),
                ('publication_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время публикации')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='FilmStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='film_studio_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('film_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.film')),
            ],
            bases=('movies.film',),
        ),
        migrations.AddField(
            model_name='film',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.franchise'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('file_path', models.CharField(max_length=2048)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.series')),
            ],
        ),
    ]
