# Generated by Django 5.0.4 on 2024-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_episode_series_delete_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], default='movie', max_length=10, verbose_name='Тип медиа'),
        ),
    ]
