# Generated by Django 5.0.4 on 2024-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_film_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='film_videos/', verbose_name='Видеофайл'),
        ),
    ]
