# Generated by Django 5.0.4 on 2024-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_film_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file_path',
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_videos/', verbose_name='Видеофайл'),
        ),
    ]
