# Generated by Django 5.0.4 on 2024-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_episode_file_path_episode_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
